- articles/how-iojs-built-a-146-person-27-language-localization-effort-in-one-day.md
原文链接 https://medium.com/@mikeal/65e5b1c49a62
有谁愿意接单的？
> @mikeal: How io.js built a 146 person, 27 language localization effort… in one day.

- CHANGELOG.md
> changelog: add qs, path and stream

- README.md
> Italic style on Chinese is a disaster.

- CHANGELOG.md
> Add General, buffer, child_process, console

- CHANGELOG.md
> Add cluster crypto dgram dns

- CHANGELOG.md
> Add events fs http net os

- articles/io-js-and-a-node-js-foundation.md
> add article io.js and a node.js Foundation

- CNAME
- LICENSE.md
- _config.yml
- _layouts/default.html
> change CNAME to cn.iojs.org

- articles/_posts/2015-2-13-simpler-stream-construction.md
> Simpler stream construction

- assets/style.scss
高亮独立的 `code` 标签
/cc @iojs/iojs-cn
> Highlight standalone code tag

- CHANGELOG.md
> add changelog 1.3.0

- articles/_posts/2015-2-20-iojs-project-governance.md
> add article io.js Project Governance

- CHANGELOG.md
> translate changelog 1.3.0

- CHANGELOG.md
> delete en line

- weekly/_posts/2015-2-20-2015-2-20.md
add translation of weekly 2.20
> add translation of weekly 2.20

- articles/_posts/2015-2-20-govern-node-right.md
For [issue 101](https://github.com/iojs/iojs-cn/issues/101). 
第一次翻译，请大家多多帮助。
> A new translation article for http://nodegovernance.io/

- articles/_posts/2015-2-20-govern-node-right.md
> fix tweet link missing some content

- CHANGELOG.md
> add changelog 1.4.2&1.4.3

- articles/_posts/2015-2-20-iojs-project-governance.md
> 翻译 GOVERNANCE.md

- weekly/_posts/2015-2-27-2015-2-27.md
changelog部分直接copy @Pana 的~
有几处没太看明白，求review~
> Translation of weekly 2.27

- CHANGELOG.md
> translate changelog 1.4.2 & 1.4.3

- weekly/_posts/2015-3-6-2015-3-6.md
> 添加 weekly 2015-3-6 原文

- CHANGELOG.md
> translate changelog 1.5.0

- weekly/_posts/2015-3-6-2015-3-6.md
第一次翻译，鸭梨好大 T_T
`fs` 那块不知道怎么翻译，求帮助~ 然后再 review 下，Thanks :)
@popomore @fengmk2
> 翻译 weekly-2015-03-06

- CHANGELOG.md
> translate changelog 1.5.1

- weekly/_posts/2015-3-13-2015-3-13.md
> 添加 2015-3-13-weekly 原文

- CHANGELOG.md
> Add 1.6.0&1.6.1 english changelog

- CHANGELOG.md
> Translate changelog 1.6.0&1.6.1

- CHANGELOG.md
> add changelog 1.6.2 & 1.6.3

- weekly/_posts/2015-3-20-2015-3-20.md
- weekly/_posts/2015-3-27-2015-3-27.md
> Add weekly 3.20 & 3.27

- CHANGELOG.md
> translate 1.6.4

- CHANGELOG.md
> Translate changlog 1.7.0&1.7.1
